---
- defaults:
    link:
      create: true
      force: true
      relink: true

- clean: ["~"]

- link:
    ~/.gitconfig: layers/common/gitconfig
    ~/.gitignore_global: layers/common/gitignore_global
    ~/.bashrc: layers/common/bashrc
    ~/.tmux.conf: layers/common/tmux.conf
    ~/.config/fish/config.fish: layers/common/config.fish
    ~/.config/fish/fishfile: layers/common/fishfile
    ~/.fonts: layers/common/fonts
    ~/.bin/docker: layers/docker

- shell:
  - curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
  - fisher install
