---
- defaults:
    link:
      create: true
      force: true
      relink: true

- shell:
    - git submodule update --init --recursive layers/vim

- link:
    ~/.vimrc: layers/vim/vimrc
    ~/.vim/bundle: layers/vim/bundle
    ~/.gvimrc: layers/vim/gvimrc
