" vim: set fen fdm=marker

" TODO: make this path relative
source ~/dotfiles/layers/vim/prelude.vim

runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" Visual {{{1
let g:sierra_Pitch=1
colorscheme sierra
set laststatus=0
set noruler


" Movement {{{1
let mapleader=","

nnoremap <silent> = :m .+1<cr>==
nnoremap <silent> - :m .-2<cr>==

vnoremap <silent> < <gv
vnoremap <silent> > >gv

nnoremap [ mzO<esc>`z
nnoremap ] mzo<esc>`z


" File save status {{{1
function! s:SetFileSaveStatus()
  if (&mod ==# 1)
    highlight LineNr ctermfg=white
  else
    highlight LineNr ctermfg=darkgray
  endif
endfunction

augroup FileSaveStatus
  autocmd!
  autocmd BufWritePost,TextChanged,TextChangedI * call <SID>SetFileSaveStatus()
augroup END

set showmode


" Plugins {{{1
" vim-easy-align {{{2
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

" vim-tmux-runner {{{2
let g:VtrStripLeadingWhitespace = 0
let g:VtrClearEmptyLines = 0
let g:VtrAppendNewline = 1
let g:VtrUseVtrMaps = 1

" insearch.vim {{{2
set hlsearch
let g:incsearch#auto_nohlsearch = 1
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

" vim-buftabline {{{2
nnoremap <C-h> :bprev<cr>
nnoremap <C-l> :bnext<cr>
