syntax enable
filetype plugin on

set noruler
set laststatus=0
set textwidth=80

set noswapfile

function! Pv_line_numbers_on()
  set foldcolumn=1
  set numberwidth=5
  set number
  set relativenumber
endfunction

function! Pv_line_numbers_off()
  set foldcolumn=6
  set nonumber
  set norelativenumber
endfunction

call Pv_line_numbers_on()
augroup LineNumbers
  autocmd!
  autocmd InsertEnter * :call Pv_line_numbers_off()
  autocmd InsertLeave * :call Pv_line_numbers_on()
augroup END

function! PvDefaultTabSettings()
  set tabstop=2
  set shiftwidth=2
  set softtabstop=2
  set expandtab
endfunction

function! PvEvilTabSettings()
  set tabstop=8
  set shiftwidth=4
  set softtabstop=4
  set noexpandtab
endfunction

call PvDefaultTabSettings()
augroup WhitespaceCleanup
  autocmd!
  autocmd FileType make,go :call PvEvilTabSettings()
  autocmd BufWritePre * :%s/\s\+$//e
  autocmd BufWritePre * :silent! retab
augroup END
